### ISSUE TITLE
01 - Crear Tabla de Símbolos

### ISSUE THREAD

**Issue by Cdca12** [Cdca12/Compilador#1]
Como desarrollador, necesito que se genere la tabla de símbolos para llevar la administración de sus atributos.

- Valor: 10 Puntos.
- Criterios de Aceptación:
    - Mostrar la tabla de símbolos con las variables declaras dentro de un clase/método/función.
    - Mostrar por lo menos los siguiente atributos:
      - Tipo de dato
      - Posición
      - Valor

**Comment by Cdca12** [comment]
Se crean las clases en 6b2e4f3112ebb9c4403daaf19ce5edeae6212148

**Comment by MauricioGR15** [comment]
Se crea la vista para mostrar resultado de la Tabla de símbolos 37e71109c78cf88fcc10353af320848df2afb192

**Comment by MauricioGR15** [comment]
> Se crea la vista para mostrar resultado de la Tabla de símbolos [37e7110](https://github.com/Cdca12/Compilador/commit/37e71109c78cf88fcc10353af320848df2afb192)

Se integra al compilador en este commit 131a616653ddfe378ed12aee35a319c19ba45b66

**Comment by Cdca12** [comment]
Se agrega el método funcional para generar la Tabla de Símbolso en 0997c6475b6a3f6879ba966c0d9cee574e467b28
