### ISSUE TITLE
04 - Validar las variables ya declaradas

### ISSUE THREAD

**Issue by Cdca12** [Cdca12/Compilador#4]
Como desarrollador necesito que se valide que no se encuentren declaradas las variables más de una vez para evitar conflicto de tipos de datos.
- Valor: 10 Puntos.
- Criterios de aceptación:
  - Al momento de finalizar la compilación, si encontró una variable que ya se encuentra declarada, muestre un mensaje con la variable y  la posición donde la estamos queriendo realizar la segunda declaración. Además, de la posición donde se declaró por primera vez.

**Comment by MauricioGR15** [comment]
Se termina en 64c84ac6930b7900c2873f79c2e2e3618b6868d0
